version: 2.1
orbs:
  aws-terragrunt: smarshorbs/aws-terragrunt@2.2.0
jobs:
  terraform:
    executor: aws-terragrunt/default
    steps:
      - aws-terragrunt/set-up:
          aws-access-key-id: AKIA6MV6QBHB6C4GLPO2
          aws-secret-access-key: 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
          aws-region: ap-south-1
          tf-version: 0.13.5
      - run: echo "namespace=\"$NAMESPACE\"" >> ./infra/common/terraform.tfvars
      - run: echo "profile=\"default\"" >> ./infra/common/terraform.tfvars
      - run: cd ./infra && terragrunt apply-all --terragrunt-non-interactive
workflows:
  terraform:
    jobs:
      - terraform:
          context:
            - Dev
